name: Ping on changes

on:
  push:
    branches:
      - master

jobs:
  ping-aem:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request upon main branch changes
        run: |
          curl -X GET "https://author-p154555-e1622215.adobeaemcloud.com/km/ping"
